version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      go:
        patterns:
          - "*"
        exclude-patterns:
          - "github.com/pomerium/*"
  - package-ecosystem: "gomod"
    target-branch: main # see https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      pomerium:
        patterns:
          - "github.com/pomerium/*"
