version: "2"
linters:
  default: none
  enable:
    - asasalint
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - errorlint
    - exhaustruct
    - gocheckcompilerdirectives
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: internal/provider/provider.go
      - linters:
          - bodyclose
          - errcheck
          - gosec
          - staticcheck
          - unused
        path: _test\.go$|^test/|^examples/|templates\.go$
      - linters:
          - gosec
        text: "G112:"
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
      - path: (.+)\.go$
        text: SA1019
      - path: (.+)\.go$
        text: G115
      - linters:
          - staticcheck
        path: (.+)\.go$
        text: QF1008
      - linters:
          - golint
          - revive
        text: should have a package comment
      - linters:
          - exhaustruct
        path-except: converter.*\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/pomerium)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
