// Code generated by internal/generate DO NOT EDIT.
package provider

import (
	types "github.com/hashicorp/terraform-plugin-framework/types"
	pomerium "github.com/pomerium/sdk-go/proto/pomerium"
)

func (c *APIToModelConverter) BearerTokenFormat(src *pomerium.BearerTokenFormat) types.String {
	if src == nil {
		return types.StringNull()
	}

	switch src.Number() {
	case 1:
		return types.StringValue("default")
	case 2:
		return types.StringValue("idp_access_token")
	case 3:
		return types.StringValue("idp_identity_token")
	default:
		return types.StringNull()
	}
}

func (c *APIToModelConverter) CodecType(src *pomerium.CodecType) types.String {
	if src == nil {
		return types.StringNull()
	}

	switch src.Number() {
	case 0:
		return types.StringValue("auto")
	case 1:
		return types.StringValue("http1")
	case 2:
		return types.StringValue("http2")
	case 3:
		return types.StringValue("http3")
	default:
		return types.StringNull()
	}
}

func (c *APIToModelConverter) HealthCheckCodecClientType(src *pomerium.HealthCheck_CodecClientType) types.String {
	if src == nil {
		return types.StringNull()
	}

	switch src.Number() {
	case 0:
		return types.StringValue("http1")
	case 1:
		return types.StringValue("http2")
	case 2:
		return types.StringValue("http3")
	default:
		return types.StringNull()
	}
}

func (c *APIToModelConverter) HealthCheckHealthStatus(src *pomerium.HealthCheck_HealthStatus) types.String {
	if src == nil {
		return types.StringNull()
	}

	switch src.Number() {
	case 1:
		return types.StringValue("healthy")
	case 2:
		return types.StringValue("unhealthy")
	case 3:
		return types.StringValue("draining")
	case 4:
		return types.StringValue("timeout")
	case 5:
		return types.StringValue("degraded")
	default:
		return types.StringNull()
	}
}

func (c *APIToModelConverter) IssuerFormat(src *pomerium.IssuerFormat) types.String {
	if src == nil {
		return types.StringNull()
	}

	switch src.Number() {
	case 0:
		return types.StringValue("IssuerHostOnly")
	case 1:
		return types.StringValue("IssuerURI")
	default:
		return types.StringNull()
	}
}

func (c *APIToModelConverter) KeyPairOrigin(src *pomerium.KeyPairOrigin) types.String {
	if src == nil {
		return types.StringNull()
	}

	switch src.Number() {
	case 1:
		return types.StringValue("user")
	case 2:
		return types.StringValue("system")
	default:
		return types.StringNull()
	}
}

func (c *APIToModelConverter) KeyPairStatus(src *pomerium.KeyPairStatus) types.String {
	if src == nil {
		return types.StringNull()
	}

	switch src.Number() {
	case 1:
		return types.StringValue("ready")
	case 2:
		return types.StringValue("pending")
	default:
		return types.StringNull()
	}
}

func (c *APIToModelConverter) LoadBalancingPolicy(src *pomerium.LoadBalancingPolicy) types.String {
	if src == nil {
		return types.StringNull()
	}

	switch src.Number() {
	case 1:
		return types.StringValue("round_robin")
	case 2:
		return types.StringValue("maglev")
	case 3:
		return types.StringValue("random")
	case 4:
		return types.StringValue("ring_hash")
	case 5:
		return types.StringValue("least_request")
	default:
		return types.StringNull()
	}
}

func (c *APIToModelConverter) MtlsEnforcementMode(src *pomerium.MtlsEnforcementMode) types.String {
	if src == nil {
		return types.StringNull()
	}

	switch src.Number() {
	case 1:
		return types.StringValue("policy")
	case 2:
		return types.StringValue("policy_with_default_deny")
	case 3:
		return types.StringValue("reject_connection")
	default:
		return types.StringNull()
	}
}

func (c *APIToModelConverter) OAuth2AuthStyle(src *pomerium.OAuth2AuthStyle) types.String {
	if src == nil {
		return types.StringNull()
	}

	switch src.Number() {
	case 1:
		return types.StringValue("in_params")
	case 2:
		return types.StringValue("in_header")
	default:
		return types.StringNull()
	}
}

func (c *APIToModelConverter) SANMatcherSANType(src *pomerium.SANMatcher_SANType) types.String {
	if src == nil {
		return types.StringNull()
	}

	switch src.Number() {
	case 1:
		return types.StringValue("email")
	case 2:
		return types.StringValue("dns")
	case 3:
		return types.StringValue("uri")
	case 4:
		return types.StringValue("ip_address")
	case 5:
		return types.StringValue("user_principal_name")
	default:
		return types.StringNull()
	}
}

func (c *APIToModelConverter) ServerType(src *pomerium.ServerType) types.String {
	if src == nil {
		return types.StringNull()
	}

	switch src.Number() {
	case 1:
		return types.StringValue("core")
	case 2:
		return types.StringValue("enterprise")
	case 3:
		return types.StringValue("zero")
	default:
		return types.StringNull()
	}
}
