// Code generated by internal/generate DO NOT EDIT.
package provider

var (
	BearerTokenFormatValues               = []string{"default", "idp_access_token", "idp_identity_token"}
	CodecClientTypeValues                 = []string{"http1", "http2", "http3"}
	CodecTypeValues                       = []string{"auto", "http1", "http2", "http3"}
	DeviceKindValues                      = []string{"fido_u2f", "android", "apple", "tpm", "windows"}
	FormatValues                          = []string{"pem"}
	IssuerFormatValues                    = []string{"IssuerHostOnly", "IssuerURI"}
	LoadBalancingPolicyValues             = []string{"round_robin", "maglev", "random", "ring_hash", "least_request"}
	OAuth2AuthStyleValues                 = []string{"in_params", "in_header"}
	PublicKeyAlgorithmValues              = []string{"pka_unknown_do_not_use", "rsa", "dsa", "ecdsa", "ed25519"}
	RedirectResponseCodeValues            = []string{"moved_permanently", "found", "see_other", "temporary_redirect", "permanent_redirect"}
	AttestationConveyancePreferenceValues = []string{"none", "indirect", "direct", "enterprise"}
	AuthenticatorAttachmentValues         = []string{"platform", "cross_platform"}
	PublicKeyCredentialTypeValues         = []string{"public_key"}
	ResidentKeyRequirementValues          = []string{"resident_key_discouraged", "resident_key_preferred", "resident_key_required"}
	UserVerificationRequirementValues     = []string{"user_verification_discouraged", "user_verification_preferred", "user_verification_required"}
)
