package main

import (
	"context"
	"errors"
	"slices"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/iancoleman/strcase"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"

	_ "github.com/pomerium/enterprise-client-go/pb"
)

func generateEnums(ctx context.Context) error {
	return errors.Join(
		generateEnterpriseToModelEnums(ctx),
		generateModelToEnterpriseEnums(ctx),
	)
}

func generateEnterpriseToModelEnums(_ context.Context) error {
	f := jen.NewFile("provider")
	f.PackageComment("// Code generated by internal/generate DO NOT EDIT.")

	prefix := "pomerium.dashboard."

	var enumDescriptors []protoreflect.EnumDescriptor
	protoregistry.GlobalTypes.RangeEnums(func(t protoreflect.EnumType) bool {
		if strings.HasPrefix(string(t.Descriptor().FullName()), prefix) {
			enumDescriptors = append(enumDescriptors, t.Descriptor())
		}
		return true
	})

	slices.SortFunc(enumDescriptors, func(x, y protoreflect.EnumDescriptor) int {
		return strings.Compare(string(x.FullName()), string(y.FullName()))
	})

	for _, desc := range enumDescriptors {
		methodName := strings.ReplaceAll(string(desc.FullName()[len(prefix):]), ".", "")
		typeName := strings.ReplaceAll(string(desc.FullName()[len(prefix):]), ".", "_")
		valuePrefix := strcase.ToScreamingSnake(string(desc.Name())) + "_"
		f.Func().
			ParamsFunc(func(g *jen.Group) {
				g.Id("c").Op("*").Id("EnterpriseToModelConverter")
			}).
			Id(methodName).
			ParamsFunc(func(g *jen.Group) {
				g.Id("src").Op("*").Qual("github.com/pomerium/enterprise-client-go/pb", typeName)
			}).
			Qual("github.com/hashicorp/terraform-plugin-framework/types", "String").
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Op("==").Nil()).Block(
					jen.Return(jen.Qual("github.com/hashicorp/terraform-plugin-framework/types", "StringNull").Call()),
				)
				g.Line()
				g.Switch(jen.Id("src").Dot("Number").Call()).BlockFunc(func(g *jen.Group) {
					for i := range desc.Values().Len() {
						valueDesc := desc.Values().Get(i)
						name := strings.TrimPrefix(string(valueDesc.Name()), valuePrefix)
						// leave issuer format in the original case
						if typeName != "IssuerFormat" {
							name = strings.ToLower(name)
						}
						if name == "unknown" || name == "undefined_do_not_use" || name == "unspecified" {
							continue
						}
						g.Case(jen.Lit(int(valueDesc.Number()))).Block(
							jen.Return(jen.Qual("github.com/hashicorp/terraform-plugin-framework/types", "StringValue").Call(jen.Lit(name))),
						)
					}
					g.Default().Block(
						jen.Return(jen.Qual("github.com/hashicorp/terraform-plugin-framework/types", "StringNull").Call()),
					)
				})
			})
		f.Line()
	}

	return f.Save("./internal/provider/converters_enterprise_to_model.gen.go")
}

func generateModelToEnterpriseEnums(_ context.Context) error {
	f := jen.NewFile("provider")
	f.PackageComment("// Code generated by internal/generate DO NOT EDIT.")

	prefix := "pomerium.dashboard."

	var enumDescriptors []protoreflect.EnumDescriptor
	protoregistry.GlobalTypes.RangeEnums(func(t protoreflect.EnumType) bool {
		if strings.HasPrefix(string(t.Descriptor().FullName()), prefix) {
			enumDescriptors = append(enumDescriptors, t.Descriptor())
		}
		return true
	})

	slices.SortFunc(enumDescriptors, func(x, y protoreflect.EnumDescriptor) int {
		return strings.Compare(string(x.FullName()), string(y.FullName()))
	})

	for _, desc := range enumDescriptors {

		methodName := strings.ReplaceAll(string(desc.FullName()[len(prefix):]), ".", "")
		typeName := strings.ReplaceAll(string(desc.FullName()[len(prefix):]), ".", "_")
		valuePrefix := strcase.ToScreamingSnake(string(desc.Name())) + "_"
		f.Func().
			ParamsFunc(func(g *jen.Group) {
				g.Id("c").Op("*").Id("ModelToEnterpriseConverter")
			}).
			Id(methodName).
			ParamsFunc(func(g *jen.Group) {
				g.Id("p").Qual("github.com/hashicorp/terraform-plugin-framework/path", "Path")
				g.Id("src").Qual("github.com/hashicorp/terraform-plugin-framework/types", "String")
			}).
			Op("*").Qual("github.com/pomerium/enterprise-client-go/pb", typeName).
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Dot("IsNull").Call().Op("||").Id("src").Dot("IsUnknown").Call()).Block(
					jen.Return(jen.Nil()),
				)
				g.Line()
				g.Switch(jen.Qual("strings", "ToLower").Call(jen.Id("src").Dot("ValueString").Call())).BlockFunc(func(g *jen.Group) {
					for i := range desc.Values().Len() {
						valueDesc := desc.Values().Get(i)
						name := strings.ToLower(strings.TrimPrefix(string(valueDesc.Name()), valuePrefix))
						if name == "unknown" || name == "undefined_do_not_use" || name == "unspecified" {
							continue
						}
						g.Case(jen.Lit(name)).Block(
							jen.Return(jen.Qual("github.com/pomerium/enterprise-client-go/pb", typeName).Call(jen.Lit(int(valueDesc.Number()))).Dot("Enum").Call()),
						)
					}
					g.Default().BlockFunc(func(g *jen.Group) {
						g.Id("c").Dot("diagnostics").Dot("AddAttributeError").Call(
							jen.Id("p"),
							jen.Lit("unknown "+typeName),
							jen.Qual("fmt", "Sprintf").Call(jen.Lit("unknown "+typeName+": %s"), jen.Id("src").Dot("ValueString").Call()),
						)
						g.Return(jen.Nil())
					})
				})
			})
		f.Line()
	}

	return f.Save("./internal/provider/converters_model_to_enterprise.gen.go")
}
