name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
        with:
          go-version: 1.24.x

      - name: Setup Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        with:
          python-version: "3.12"

      - name: Setup Pre-Commit
        run: python -m pip install pre-commit

      - name: Run Pre-Commit
        run: pre-commit run --show-diff-on-failure --color=always
