name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: 1.24.x

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: "3.12"

      - name: Setup Pre-Commit
        run: python -m pip install pre-commit

      - name: Run Pre-Commit
        run: pre-commit run --show-diff-on-failure --color=always
