name: Tests
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: 1.24.x

      - name: Run tests
        run: make test

      - name: Run acceptance tests
        run: |
          go test -v ./internal/provider/... -timeout 120m
        env:
          TF_ACC: "1"
          POMERIUM_API_URL: ${{ secrets.POMERIUM_API_URL }}
          POMERIUM_API_TOKEN: ${{ secrets.POMERIUM_API_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: golangci/golangci-lint-action@2226d7cb06a077cd73e56eedd38eecad18e5d837
        with:
          version: v1.64.8
          args: --timeout=10m
